language: generic
services:
  - docker

before_install:
  - docker build -t nurul3101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nurul3101/docker-react npm run test -- --coverage
