language: generic
services:
  - docker

before_install:
  - docker build -t nurul3101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nurul3101/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-378997148642"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
